project_name: slide-serve

builds:
- env:
  - CGO_ENABLED=0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  prerelease: auto

brew:
  github:
    owner: mpas
    name: homebrew-slide-serve
  folder: Formula
  homepage: https://github.com/cdreier/slide-serve
  description: |
    Small presentation and dev server for simple slides, based on https://github.com/trikita/slide-html